In [1]:
import numpy as np
import random
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Apibrėžiam duomenų matricą, pirmas stulpelis yra poslinkis
duomenys = np.matrix([[1, -0.2, 0.5], 
                       [1, 0.2, -0.7], 
                       [1, 0.8, -0.8], 
                       [1, 0.8, 1]])

# Inicializuojame svorius (b, w1, w2) nuliu
svoriai = np.array([0, 0, 0])

# Apibrėžiam tikras klases, atitinkančias kiekvieną duomenų tašką
tikra_klase = np.array([0, 0, 1, 1])


In [3]:
def slenkstine(duomenys, svoris):
    klase_slen = []
    
    for row in duomenys:
        if row @ svoris.T >= 0:
            klase_slen.append(1) 
        else:
            klase_slen.append(0)
            
    return klase_slen


def sigmoidine(duomenys, svoris):
    klase_sigm = []
    
    for row in duomenys:
        z = row @ svoris.T
        f = 1 / (1 + np.exp(-z))
        if f >= 0.5:
            klase_sigm.append(1)
        else:
            klase_sigm.append(0)
        
    return klase_sigm


# Funkcija, skirta svorių radimui iš intervalo pagal aktyvacijos funkciją 
def klasifikacija(intervalas, duomenys, tikra_klase, aktyvacijos_f):
    tinkami_svoriai = []
    bandymai = 0  
    bandymai_pirmas_tinkamas = None  # Skaičius, kai randame pirmą tinkamą svorį

    for w1 in intervalas:
        for w2 in intervalas:
            for b in intervalas:
                svoris = np.array([b, w1, w2])
                
                # Klasifikuojame naudodami pasirinktą aktyvacijos funkciją
                klases = aktyvacijos_f(duomenys, svoris)
                
                bandymai += 1 
                
                # Tikriname, ar gautos klasės atitinka tikras klases
                if np.array_equal(klases, tikra_klase.flatten()):
                    tinkami_svoriai.append(svoris)
                    print(f"Poslinkis b: {svoris[0]}, Svoriai w1: {svoris[1]}, w2: {svoris[2]}")
                    
                    # Jei tai pirmas tinkamas svoris, fiksuojame bandymų skaičių
                    if bandymai_pirmas_tinkamas is None:
                        bandymai_pirmas_tinkamas = bandymai
    
    return np.array(tinkami_svoriai), bandymai_pirmas_tinkamas


# Funkcija, skirta atsitiktinių svorių paieškai pagal aktyvacijos funkciją
def random_svoriai_klasifikacija(intervalas, duomenys, tikra_klase, aktyvacijos_f, svoriu_sk):
    tinkami_svoriai = []
    bandymai = 0
    while len(tinkami_svoriai) < svoriu_sk:
        # Atsitiktinai pasirenkame svorius iš nustatyto intervalo
        svoris = np.array([random.choice(intervalas), 
                           random.choice(intervalas), 
                           random.choice(intervalas)])
        
        # Klasifikuojame naudodami pasirinktą aktyvacijos funkciją
        klases = aktyvacijos_f(duomenys, svoris)
        bandymai += 1
        # Tikriname, ar gautos klasės atitinka tikras klases
        if np.array_equal(klases, tikra_klase):
            tinkami_svoriai.append(svoris)
            print(f"Poslinkis b: {svoris[0]}, Svoriai w1: {svoris[1]}, w2: {svoris[2]}")

    return np.array(tinkami_svoriai), bandymai

## Uzdaviniai su slenkstine aktyvacijos funkcija

In [4]:
# Nustatome svorių intervalą nuo -2 iki 2 su 0.2 žingsniu
intervalas = np.arange(-2, 2, 0.2)

tinkami_svoriai, bandymai = klasifikacija(intervalas, duomenys, tikra_klase, slenkstine)

print("\nTinkami svoriai gauti slenkstine funkcija:\n", np.round(tinkami_svoriai, 1), "\n\nBandymai iki pirmo tinkamo svorio: ", bandymai)
print(len(tinkami_svoriai))

Poslinkis b: -0.2000000000000004, Svoriai w1: 0.39999999999999947, w2: -4.440892098500626e-16
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.5999999999999996, w2: -4.440892098500626e-16
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.5999999999999996, w2: -4.440892098500626e-16
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.5999999999999996, w2: 0.1999999999999993
Poslinkis b: -4.440892098500626e-16, Svoriai w1: 0.5999999999999996, w2: 0.1999999999999993
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.7999999999999994, w2: -0.2000000000000004
Poslinkis b: -0.6000000000000003, Svoriai w1: 0.7999999999999994, w2: -4.440892098500626e-16
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.7999999999999994, w2: -4.440892098500626e-16
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.7999999999999994, w2: -4.440892098500626e-16
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.7999999999999994, w2: 0.1999999999999993
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.7999999999999994, w2: 0.19999

In [5]:
# Pasirenkame 5 atsitiktinius svorius
reiksmes = np.random.choice(len(tinkami_svoriai), 5, replace=False)

for idx in reiksmes:
    svoris = tinkami_svoriai[idx]    
    klases = slenkstine(duomenys, svoris)
    print(f"Naudojant svorius: {np.round(svoris, 1)}, gauta klasė: {klases}")

Naudojant svorius: [-1.   1.8  0.4], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.6  1.8  0.8], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-1.   1.8 -0. ], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.4  0.8 -0.2], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.4  1.2 -0.2], gauta klasė: [0, 0, 1, 1]


In [16]:
tinkami_svoriai, bandymai = random_svoriai_klasifikacija(intervalas, duomenys, tikra_klase, slenkstine, 5)

print("\nTinkami svoriai gauti slenkstine funkcija:\n", np.round(tinkami_svoriai, 1), "\n\nVisi bandymai: ", bandymai)

Poslinkis b: -0.6000000000000003, Svoriai w1: 1.799999999999999, w2: -4.440892098500626e-16
Poslinkis b: -0.8000000000000003, Svoriai w1: 1.5999999999999992, w2: -0.40000000000000036
Poslinkis b: -1.2000000000000002, Svoriai w1: 1.799999999999999, w2: 0.1999999999999993
Poslinkis b: -0.8000000000000003, Svoriai w1: 1.1999999999999993, w2: -4.440892098500626e-16
Poslinkis b: -1.0000000000000002, Svoriai w1: 1.5999999999999992, w2: -4.440892098500626e-16

Tinkami svoriai gauti slenkstine funkcija:
 [[-0.6  1.8 -0. ]
 [-0.8  1.6 -0.4]
 [-1.2  1.8  0.2]
 [-0.8  1.2 -0. ]
 [-1.   1.6 -0. ]] 

Visi bandymai:  295


In [7]:
for svoris in tinkami_svoriai:
    klases = slenkstine(duomenys, svoris)
    print(f"Naudojant svorius: {np.round(svoris, 1)}, gauta klasė: {klases}")

Naudojant svorius: [-0.2  0.8  0.4], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.6  1.8 -0. ], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.2  1.6  0.4], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.4  0.8 -0. ], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.8  1.4  0.2], gauta klasė: [0, 0, 1, 1]


## Uzdaviniai su sigmoidine aktyvacijos funkcija

In [8]:
# Nustatome svorių intervalą nuo -2 iki 2 su 0.2 žingsniu
intervalas = np.arange(-2, 2, 0.2)

tinkami_svoriai, bandymai = klasifikacija(intervalas, duomenys, tikra_klase, sigmoidine)

print("\nTinkami svoriai gauti sigmoidine funkcija:\n", np.round(tinkami_svoriai, 1), "\n\nBandymai iki pirmo tinkamo svorio: ", bandymai)
print(len(tinkami_svoriai))

Poslinkis b: -0.2000000000000004, Svoriai w1: 0.39999999999999947, w2: -4.440892098500626e-16
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.5999999999999996, w2: -4.440892098500626e-16
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.5999999999999996, w2: -4.440892098500626e-16
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.5999999999999996, w2: 0.1999999999999993
Poslinkis b: -4.440892098500626e-16, Svoriai w1: 0.5999999999999996, w2: 0.1999999999999993
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.7999999999999994, w2: -0.2000000000000004
Poslinkis b: -0.6000000000000003, Svoriai w1: 0.7999999999999994, w2: -4.440892098500626e-16
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.7999999999999994, w2: -4.440892098500626e-16
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.7999999999999994, w2: -4.440892098500626e-16
Poslinkis b: -0.40000000000000036, Svoriai w1: 0.7999999999999994, w2: 0.1999999999999993
Poslinkis b: -0.2000000000000004, Svoriai w1: 0.7999999999999994, w2: 0.19999

In [9]:
# Pasirenkame 5 atsitiktinius svorius
reiksmes = np.random.choice(len(tinkami_svoriai), 5, replace=False)

for idx in reiksmes:
    svoris = tinkami_svoriai[idx]    
    klases = sigmoidine(duomenys, svoris)
    print(f"Naudojant svorius: {np.round(svoris, 1)}, gauta klasė: {klases}")


Naudojant svorius: [-0.6  1.2 -0. ], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.6  1.6 -0. ], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.2  1.8  0.4], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.8  1.8 -0.4], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.6  1.8 -0.2], gauta klasė: [0, 0, 1, 1]


In [10]:
tinkami_svoriai, bandymai = random_svoriai_klasifikacija(intervalas, duomenys, tikra_klase, sigmoidine, 5)

print("\nTinkami svoriai gauti slenkstine funkcija:\n", np.round(tinkami_svoriai, 1), "\n\nVisi bandymai: ", bandymai)

Poslinkis b: -0.8000000000000003, Svoriai w1: 1.5999999999999992, w2: -0.2000000000000004
Poslinkis b: -0.2000000000000004, Svoriai w1: 1.799999999999999, w2: 0.7999999999999994
Poslinkis b: -0.40000000000000036, Svoriai w1: 1.1999999999999993, w2: 0.1999999999999993
Poslinkis b: -0.6000000000000003, Svoriai w1: 0.7999999999999994, w2: -4.440892098500626e-16
Poslinkis b: -0.6000000000000003, Svoriai w1: 1.799999999999999, w2: -0.2000000000000004

Tinkami svoriai gauti sigmoidine funkcija:
 [[-0.8  1.6 -0.2]
 [-0.2  1.8  0.8]
 [-0.4  1.2  0.2]
 [-0.6  0.8 -0. ]
 [-0.6  1.8 -0.2]] 

Bandymai iki pirmo tinkamo svorio:  430


In [11]:
for svoris in tinkami_svoriai:
    klases = sigmoidine(duomenys, svoris)
    print(f"Naudojant svorius: {np.round(svoris, 1)}, gauta klasė: {klases}")

Naudojant svorius: [-0.8  1.6 -0.2], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.2  1.8  0.8], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.4  1.2  0.2], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.6  0.8 -0. ], gauta klasė: [0, 0, 1, 1]
Naudojant svorius: [-0.6  1.8 -0.2], gauta klasė: [0, 0, 1, 1]
